name: Blater API

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Blater's Registry
        uses: docker/login-action@v3
        with:
          #registry: registry.blater.tech/blater
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Checkout Core
        uses: actions/checkout@v4
        with:
          repository: BlaterTech/Blater
          path: blater/Blater
      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          repository: BlaterTech/Blater.SDK
          path: blater/Blater.SDK
      - name: Checkout Frontend
        uses: actions/checkout@v4
        with:
          repository: BlaterTech/Blater.Frontend
          path: blater/Blater.Frontend
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: blater/Blater.Portal
      #- name: Test the whole solution
      #  working-directory: blater/Blater.Portal
      #  run: dotnet test --verbosity normal src/Blater.Internals.sln
      - name: Publish
        working-directory: blater/Blater.Portal
        run: dotnet publish src/Blater.Portal/Blater.Portal/Blater.Portal.csproj -c Release -r linux-x64 -p:ContainerRepository=Blater.Portal -p:ContainerImageTag=latest /t:PublishContainer
      #- name: Docker Deploy
      #  run: |
      #    export VERSION=$(date --utc '+%Y%m%d%H%M')
      #    docker tag blater-demo:latest registry.blater.tech/blater/blater-demo:${{github.REF_NAME}}-$VERSION
      #    docker push registry.blater.tech/blater/blater-demo:${{github.REF_NAME}}-$VERSION
      - name: Docker Deploy
        run: |
          export VERSION=$(date --utc '+%Y%m%d%H%M')
          docker tag Blater.Portal:latest autosystem/Blater.Portal:${{github.REF_NAME}}-$VERSION
          docker push autosystem/Blater.Portal:${{github.REF_NAME}}-$VERSION
          docker push autosystem/Blater.Portal:latest
